import type { Metadata } from 'next';

import './globals.css';
import { AuthProvider } from './Providers';

export const metadata: Metadata = {
  title: 'be10X',
  description: 'Generated by Indrasena Reddy',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className='w-screen h-screen bg-slate-200'>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
